### PR TITLE
fixes https://github.com/ros-drivers/rosserial/issues/8

### PR DESCRIPTION
**Pull request by xaedes**
when transmission errors caused the previous read request to timeout, serial_node crashed

### CODE REVIEW

**Comment by mikepurvis** [comment]
LGTM.

**Comment by xaedes** [comment]
Would be nice, if this could be accepted as it is a somehow serious issue as it crashes the node.

**Comment by mikepurvis** [comment]
Yes, I agree—I don't have the commit privileges to merge it, though. @PaulBouchier ?

**Comment by mikeferguson** [comment]
LGTM and appears to be quite similar to the other checks already implemented.

**Pull request merged**
