### PR TITLE
added time out to the state machine

### PR DESCRIPTION
**Pull request by jscatena88**
Implmented as indicated in issue #128

### CODE REVIEW

**Comment by mikepurvis** [comment]
Should we also set `configured_ = false`?

Also, that line is now really long. I know it's consistent with the surrounding conditionals, but could you please move the comment to right above the return, inside the braces?

**Comment by jscatena88** [comment]
Yeah setting configured_ false seems like a good idea as well.

And no problem with the comment, I wasn't sure wether to prioritize consistency or reasonable line lengths.

**Comment by mikepurvis** [comment]
Looks great, thanks!

**Comment by mikepurvis** [comment]
Ugh, this is causing a problem for me now due to difftime. Is there any reason to use that vs. just a straight subtraction? The `time()` function should either return an unsigned integer value or something which supplies `operator-`.

Thoughts?

**Pull request merged**
