### PR TITLE
examples/ADC/ADC.pde: rosserial_arduino -> rosserial_mbed

### PR DESCRIPTION
**Pull request by s-t-a-n**
rosserial_arduino/src/ros_lib/examples/ADC/ADC.pde does not compile. It seems that the ADC components in  rosserial_arduino were recently moved to rosserial_mbed. Changing rosserial_arduino to rosserial_mbed does the trick.

Tested with:
* Arduino IDE 1.8.13
* Arduino-CI 1.3

ROSserial headers generated from noetic-devel using:
* python-pyserial 3.5-1
* ros-noetic-roscpp-serialization 0.7.1-1

### CODE REVIEW

**Comment by romainreignier** [comment]
Mbed and Arduino are distinct frameworks, there is no point to mix the two.
The [Adc.msg file](https://github.com/ros-drivers/rosserial/blob/dfc147ec379ad6cdbe83e3ed99d44e35ea0ec29b/rosserial_arduino/msg/Adc.msg) has not been changed for 10 years.
The issue is elsewhere.

**Comment by s-t-a-n** [comment]
The problem seems to be in the call to catkin_python_setup() in rosserial_arduino/CMakeLists.txt. Commenting it yields the generation of the rosserial_arduino messages.

I'll have a further look into it.

**Comment by s-t-a-n** [comment]
Ah luckily someone already found out what's bugging: #519 

> This is related to #504, and is fixed by #521 

I can confirm this is fixed by #521

**Comment by romainreignier** [comment]
Thanks for digging into the issue.

**Pull request closed without merging**
