### PR TITLE
Enhance ArduinoTcpHardware

### PR DESCRIPTION
**Pull request by bochen87**
- Add support to check for current TCP connection status
- stop tcp before re-connecting (sometimes it fails to reconnect and hangs indefinitely and stopping the tcp first helps with this scenario)

### CODE REVIEW

**Comment by romainreignier** [comment]
I did not try the changes but they seems legitimate.

But I am wondering how do you use that code? Because the hardware's `init()` method is only called from the `NodeHandle::initNode()` which should only be called once per program.

**Comment by bochen87** [comment]
The node handle has a hardware object - you can access it by calling the getHardware() function https://github.com/ros-drivers/rosserial/blob/fe1e233f39d56931b5e223c5e53a2d9c2f9fb664/rosserial_client/src/ros_lib/ros/node_handle.h#L153

**Comment by romainreignier** [comment]
@bochen87 Ok, that is what I thought. So sometime in your firmware, you detect that there is an issue with the connection and you re-call the `init()` method?

**Comment by bochen87** [comment]
exactly, In my main loop every few iterations i check the conn status and reconnect if needed.

**Comment by romainreignier** [comment]
@bochen87 Ok, I see. Interesting.

I have never tried the ArduinoTcpHardware in a long run but if it useful to `init()` we should add it to the examples.

**Review by romainreignier — APPROVED** [review]

**Comment by bochen87** [comment]
Since changes are approved, can somebody merge pls?

**Comment by mikepurvis** [comment]
Sorry for the delay!

**Pull request merged**
