### PR TITLE
Adding inWaiting method to FakeSerial class. Fixing issue #179

### PR DESCRIPTION
**Pull request by lucasplus**
This is my first pull request. So please let me know if I messed something up. I had the same [issue](https://github.com/ros-drivers/rosserial/issues/179) as @rmolin88. I made this change and it got rid of the error for me. My fix seems a little simple so please review. And yay open source!

### CODE REVIEW

**Comment by mikepurvis** [comment]
Looks perfect, thanks!

**Comment by tricktux** [comment]
awesome! Thanks a lot! will be a try asap!

**Comment by lucasplus** [comment]
Awesome. I have a question @mikepurvis . How long usually until the debian package is updated? I don't if I'm saying that right. Meaning until `sudo apt-get install ros-indigo-rosserial` will have the change I just created. I know that question isn't relevant to this issue. I apologize. I wasn't sure what to google to get the answer.

**Comment by mikepurvis** [comment]
Committed to `jade-devel` in 6da09b007cc77dd649d0be51d269296f9124eee9.

In terms of timing, I probably won't cut a release for a few weeks, and then it'll be another few after that before the built packages are released to ros/public. For now, you should clone the rosserial git repo into your source workspace.

**Comment by lucasplus** [comment]
Thanks for the information :+1:

**Pull request merged**
