### PR TITLE
Fixes Issue #86

### PR DESCRIPTION
**Pull request by mgerdzhev**
Fixed the deserialize() of AVR_Float64DataType in order to support negative numbers.
This should resolve issue #86

### CODE REVIEW

**Comment by mikepurvis** [comment]
Hi @mgerdzhev, thanks for the contribution! Can you explain what your process was for testing and verifying this?

**Comment by mgerdzhev** [comment]
hi @mikepurvis. I am using the Float64DataType as part of geometry_msgs/Twist. If I send it negative numbers and print them out they always show up as -0.0 due to the sign bit not properly being set. With the current change, the sign bit is copied from the 64bit to the 32bit representation and my Twist messages are received and printed properly (negative and positive). I tested it out on our robot and the message is interpreted properly now.

**Comment by mikeferguson** [comment]
This seems reasonable, although I'm entirely sure how this came to be broken in the first place (it did used to work)...

@mikepurvis you can do a quick test locally with this sketch: https://github.com/ros-drivers/rosserial/blob/hydro-devel/rosserial_arduino/src/ros_lib/tests/float64_test/float64_test.pde which lets you send float messages down, subtract 1 and return it.

**Comment by mikepurvis** [comment]
Okay, should be able to get to this on the weekend, thanks again.

**Comment by mikepurvis** [comment]
This fix is merging as part of #144.

**Pull request closed without merging**
