### PR TITLE
Changed the build system to catkin for rosserial_xbee

### PR DESCRIPTION
**Pull request by tonybaltovski**
I have changed the build system for rosserial_xbee to catkin which as been placed in the metapackage rossserial_experimental for since ROS groovy.  I have tested this using a pair of series 1 xbees and it worked.  I think this would be a useful package for wireless serial communication.  Can someone else verify that it works as well? 

-Tony

### CODE REVIEW

**Comment by mikeferguson** [comment]
@balt0 This pull request appears to include build directory, as well as a number of temporary files (CMakeLists.txt~ and setup.py~). Those have to go away before this can be merged.

**Comment by mikeferguson** [comment]
@balt0 also a couple .pyc files.

**Comment by mikeferguson** [comment]
I manually merged this in, without build folder or history of all those files.

**Comment by tonybaltovski** [comment]
Thanks Mike  for merging this manually.  I started deleting the extra files but I could not delete the build directory from the website and I don't have access to my Linux machine.  Has anyone else tested this?

**Comment by mikeferguson** [comment]
It doesn't "break" the build, but the install is definitely not quite right -- I'm working on that right now (but in the process found something else in my workspace has a busted install as well, so I'm fixing that first)

**Comment by mikeferguson** [comment]
Ok, f9b71ab960abe2948e7e63cdb67b4068fdddb293 makes this installable by catkin (which means it will work on the buildfarm), I don't have an actual setup to test against, but it appears that all scripts are running, if you get a chance at some point, perhaps you can try it out on real hardware.

**Comment by tonybaltovski** [comment]
Works like a charm.  Thank you.

**Pull request closed without merging**
