### PR TITLE
 Pull request for: rosserial arduino use PROGMEM in roslib for storing md5sum, message type, etc. #143 

### PR DESCRIPTION
**Pull request by strothmw**
Pull request for solving the above issue (Using PROGMEM to reduce SRAM usage of ros_lib on Arduino)

### CODE REVIEW

**Comment by strothmw** [comment]
Fixes #143

**Comment by mikepurvis** [comment]
This intrigues me, and I appreciate the effort to document in the other ticket, but I'm still a little nervous about the amount of stuff being added.

How confident are you that the changes will not negatively impact non-serial users, non-Arduino users, and non-AVR users?

**Comment by strothmw** [comment]
Are there any differences for running rosserial_emebedded_linux examples on a standard PC? If not maybe I can merge this with the jade devel branch for my fork an run the examples for embedded linux and the samples for rosserial_windowsand we can see if we will merge this into the jade devel branch.

For Arduino I've been using this very much during the last month, really notable more stable behaviour of the device!

**Comment by AlexisTM** [comment]
Isn't it sufficient to use F macro (from http://playground.arduino.cc/Learning/Memory) ?
(I never used it and I am just wondering)

**Comment by strothmw** [comment]
No, you can't. Because the original rosserial loginfo, logerror etc. functions of the nodehandle only accept const char* as input while the F macro "returns" a type const __FlashStringHelper * , i.e. you cannot pass it to the normal rosserial  loginfo, logerror etc. functions. The "Serial.println" of arduino is overloaded and has implementations for both,   const __FlashStringHelper *, const char* . Hence, you can use "Serial.println" with the F macro but not the normal rosserial loginfo, logerror etc. functions.

That's why I templated the methods in my fork (https://github.com/strothmw/rosserial/blob/indigo-devel/rosserial_client/src/ros_lib/ros/node_handle.h#L581) and use a base class ReadoutBuffer that by default just passes the const char* to the message function but for arduino is specialized to a FlashReadoutBuffer (https://github.com/strothmw/rosserial/blob/indigo-devel/rosserial_arduino/src/ros_lib/ros.h#L48) that still passes the const char* s but calls readFromFlash for the const __FlashStringHelper * s.

This allows using the loginfo, logerror, etc functions with both const char* strings and flash strings like here:
https://github.com/strothmw/rosserial/blob/indigo-devel/rosserial_arduino/src/ros_lib/examples/HelloWorldFlash/HelloWorldFlash.pde#L54

Passing the msg types / md5s  to the flash is simple, just requires overriding in the header generator for arduino, see https://github.com/strothmw/rosserial/blob/indigo-devel/rosserial_arduino/src/rosserial_arduino/make_libraries.py#L100. Here the PSTR macro assures the values stay in flash.

Unfortunately both PSTR and F only work inside function scopes. That's why for topics you need the PROGMEN keyword on a variable separat from the publisher object like here:
https://github.com/strothmw/rosserial/blob/indigo-devel/rosserial_arduino/src/ros_lib/examples/HelloWorldFlash/HelloWorldFlash.pde#L25

**Comment by AlexisTM** [comment]
I appreciate your explanation!  This PR is awesome and is probably needed in some projects!

**Comment by dkargin** [comment]
I've made an updated version of your pull request #295

Great job, it really allows us to make a more subscribers/publishers before RAM is completely exhausted on arduino (mega2560, mega328) side.

**Comment by mikepurvis** [comment]
Closing in favour of #295.

**Pull request closed without merging**
