### PR TITLE
add support to STM32Duino Ethernet library (Arduino platform)

### PR DESCRIPTION
**Pull request by ketchup007**

### CODE REVIEW

**Comment by romainreignier** [comment]
Thanks for the contribution.
I will try to test it soon.

**Comment by romainreignier** [comment]
Ok, I have tried it.
We should document the
```C++
#define STM32ETHERNET
```
to use in the user code.

**Comment by romainreignier** [comment]
I have added a table to list the different `#define` in the [rosserial_arduino wiki page](http://wiki.ros.org/rosserial_arduino).

**Comment by youliangtan** [comment]
Friendly ping, is there any plan to merge this in?

**Pull request closed without merging**
