### PR TITLE
Fixing build error by removing disambigous argument.

### PR DESCRIPTION
**Pull request by spaghetti-**
http://stackoverflow.com/questions/7007817/a-confusing-detail-about-the-most-vexing-parse

### CODE REVIEW

**Comment by mikeferguson** [comment]
Looks fine to me -- out of curiosity, which compiler was barfing on this?

**Comment by spaghetti-** [comment]
`Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)`

**Comment by spaghetti-** [comment]
Error message from the build if you're interested in that as well.

```
/Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/Session.h:331:56: error: variable length array of non-POD element type 'std::string'
      (aka 'basic_string<char, char_traits<char>, allocator<char> >')
      std::string required_topic(std::string(param_list[i]));
                                                       ^
/Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/Session.h:331:33: warning: parentheses were disambiguated as a function declaration [-Wvexing-parse]
      std::string required_topic(std::string(param_list[i]));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/Session.h:331:34: note: add a pair of parentheses to declare a variable
      std::string required_topic(std::string(param_list[i]));
                                 ^
                                 (                     )
In file included from /Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/socket_node.cpp:40:
/Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/Session.h:331:56: error: variable length array of non-POD element type 'std::string'
      (aka 'basic_string<char, char_traits<char>, allocator<char> >')
      std::string required_topic(std::string(param_list[i]));
                                                       ^
/Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/Session.h:331:33: warning: parentheses were disambiguated as a function declaration [-Wvexing-parse]
      std::string required_topic(std::string(param_list[i]));
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alex/Code/rosserial_ws/src/rosserial/rosserial_server/src/Session.h:331:34: note: add a pair of parentheses to declare a variable
      std::string required_topic(std::string(param_list[i]));
                                 ^
                                 (                     )
1 warning and 1 error generated.
```

**Comment by mikeferguson** [comment]
Thanks for the details!

**Comment by spaghetti-** [comment]
No problem!

**Comment by spaghetti-** [comment]
@mikeferguson since you don't have an email account listed on your page, I'm contacting you through this method but I was wondering how much loss in precision can be expected when sending data over a ros publisher from an arduino using rosserial? I'm having some severe issues with it.

**Comment by mikeferguson** [comment]
What exactly do you mean loss in "precision"?

**Pull request merged**
